# version: "2.4"
# services:
 # my-nextjs-program: 
  #build: .
  #ports: 
    #- "3000:3000"


version: "3"
services:
  web: 
    build: 
      context: . 
      dockerfile: Dockerfile
    container_name: web
    restart: always
    command: yarn start
    ports:
      - 3000:3000

